import "./style.css";
import { demoOffice, labels, activities, executionState, type Agent, type Room, type Activity, validateOffice, roomSlot, assignActivity } from "./model";
let office=demoOffice(), selectedRoom="", selectedAgent="", filter:Activity|""="", zoom=1, dx=0,dy=0,simulating=false,simTimer:ReturnType<typeof setInterval>|undefined;
let lastSuccessfulReadAt:string|null=null;
let activeTab:"map"|"list"|"mcp"=matchMedia("(max-width: 700px)").matches?"list":"map";
const $=<T extends Element=HTMLElement>(s:string)=>document.querySelector(s) as T;
const escape=(s:string)=>s.replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]!));
function time(s:string){return new Date(s).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"});}
function bit(a:Agent,x:number,y:number,scale=1){const sleepy=a.activity==="offline";return `<g transform="translate(${x},${y}) scale(${scale})" class="pet-hit" role="button" tabindex="0" data-agent="${a.id}" aria-label="${escape(a.name)}，${labels[a.activity]}"><rect x="-20" y="-23" width="40" height="44" fill="transparent"/><g class="pet ${simulating&&!sleepy?"bounce":""}"><path d="M-13 -12v-8h7v6h12v-6h7v8h4v24h-4v5h-7v-5H-6v5h-7v-5h-4v-24z" fill="${a.color}" opacity="${sleepy?".48":"1"}"/><path d="${sleepy?"M-8 -2h5M3 -2h5":"M-7 -4v4M6 -4v4"}" stroke="#14171b" stroke-width="3"/>${a.activity==="meeting"||a.activity==="discussing"?'<path d="M15 -27h18v12H21l-4 5v-5h-2z" fill="#666b78"/><path d="M19 -22h10" stroke="#dadde3" stroke-width="2"/>':""}${sleepy?'<text x="20" y="-15" class="zzz">z</text>':""}${a.activity==="resting"?'<path d="M11 6h9v8h-9zM20 8h4v4h-4" fill="#d2af77"/>':""}${a.activity==="fishing"?'<path d="M15 10l18 -29 17 17" stroke="#baac91" fill="none" stroke-width="2"/>':""}</g><text y="36" class="pet-name">${escape(a.name)}</text><circle cx="21" cy="29" r="3" fill="${a.online?"#88b9a0":"#676d7a"}"/></g>`;}
function furniture(r:Room){
 const {x,y,w,h}=r;const c="#6d6159",edge="#363c45";
 if(r.kind==="meeting")return `<rect x="${x+w/2-74}" y="${y+90}" width="148" height="91" rx="5" fill="#51483f" stroke="#786a58"/><path d="M${x+45} ${y+15}h${w-90}" stroke="#777f94" stroke-width="6"/>${[0,1,2].map(i=>`<rect x="${x+w/2-64+i*51}" y="${y+77}" width="28" height="10" rx="2" fill="${edge}"/><rect x="${x+w/2-64+i*51}" y="${y+185}" width="28" height="10" rx="2" fill="${edge}"/>`).join("")}`;
 if(r.kind==="discussing")return `<circle cx="${x+w/2}" cy="${y+139}" r="56" fill="#595145" stroke="#8a785e"/><rect x="${x+w-85}" y="${y+18}" width="63" height="39" rx="3" fill="#514957"/><path d="M${x+w-76} ${y+28}h17m4 0h17m-38 11h17" stroke="#b3a290" stroke-width="6"/>`;
 if(r.kind==="working")return Array.from({length:16},(_,i)=>{const a=x+35+(i%4)*94,b=y+65+Math.floor(i/4)*48;return `<rect x="${a}" y="${b}" width="65" height="29" rx="2" fill="${c}" stroke="#89725b"/><rect x="${a+19}" y="${b+5}" width="29" height="16" rx="1" fill="#252c38"/><path d="M${a+22} ${b+22}h23" stroke="#a69d8c" stroke-width="2"/><rect x="${a+25}" y="${b+32}" width="21" height="9" rx="2" fill="${edge}"/>`;}).join("");
 if(r.kind==="resting")return `<rect x="${x+17}" y="${y+54}" width="${w-34}" height="43" rx="3" fill="#665b4a"/><rect x="${x+27}" y="${y+58}" width="30" height="25" fill="#353b40"/><circle cx="${x+78}" cy="${y+72}" r="10" fill="#889292"/><rect x="${x+w-60}" y="${y+110}" width="40" height="69" rx="4" fill="#5a6269"/><path d="M${x+w-60} ${y+136}h40" stroke="#303940"/><circle cx="${x+70}" cy="${y+206}" r="30" fill="#615b4d"/>`;
 if(r.kind==="fishing")return `<ellipse cx="${x+w/2}" cy="${y+h/2+7}" rx="67" ry="42" fill="#345e69" stroke="#638a86" stroke-width="8"/><path d="M${x+94} ${y+141}h25m-9 16h23" stroke="#78999e" stroke-width="2"/><rect x="${x+18}" y="${y+53}" width="88" height="28" rx="8" fill="#635b61"/><rect x="${x+w-55}" y="${y+50}" width="34" height="49" rx="4" fill="#454753"/>`;
 return [0,1].map(i=>`<rect x="${x+32+i*98}" y="${y+86}" width="65" height="136" rx="13" fill="#3b3e4d" stroke="#656475"/><rect x="${x+42+i*98}" y="${y+100}" width="45" height="28" rx="6" fill="#777080"/><rect x="${x+32+i*98}" y="${y+151}" width="65" height="71" rx="10" fill="#5c596c"/>`).join("");
}
function occupants(r:Room){return office.agents.filter(a=>a.roomId===r.id);}
function mapSVG(){
 const width=Math.max(1260,...office.rooms.map(r=>r.x+r.w+40));
 return `<svg id="floor" viewBox="0 0 ${width} 720" aria-label="Bit 小屋办公室户型图" xmlns="http://www.w3.org/2000/svg"><defs><pattern id="tiles" width="22" height="22" patternUnits="userSpaceOnUse"><path d="M22 0H0V22" fill="none" stroke="#353a40" stroke-width=".5"/></pattern></defs><g id="floor-content" transform="translate(${dx} ${dy}) scale(${zoom})"><rect x="8" y="8" width="${width-16}" height="687" rx="8" fill="#252a2f" stroke="#62676e" stroke-width="8"/><rect x="16" y="299" width="${width-32}" height="77" fill="url(#tiles)"/><path d="M80 341H${width-50}" stroke="#464b50" stroke-dasharray="8 9"/><text x="89" y="329" class="corridor-label">走廊</text><path d="M15 309v58m0 -4h52m-52 -52a52 52 0 0 1 52 52" fill="none" stroke="#858377" stroke-width="2"/><text x="28" y="350" class="tiny">入口</text>
 ${office.rooms.map(r=>`<g class="room-hit ${selectedRoom===r.id?"selected":""}" role="button" tabindex="0" data-room="${r.id}" aria-label="${escape(r.name)}，${occupants(r).length}/${r.capacity}"><rect x="${r.x}" y="${r.y}" width="${r.w}" height="${r.h}" rx="3" fill="${r.kind==="meeting"?"#2e2d37":r.kind==="discussing"?"#31342e":r.kind==="fishing"?"#263338":r.kind==="offline"?"#282b34":"#303333"}" stroke="#65676b" stroke-width="5"/>${r.kind==="resting"?`<rect x="${r.x+5}" y="${r.y+5}" width="${r.w-10}" height="${r.h-10}" fill="url(#tiles)"/>`:""}<path d="M${r.x+30} ${r.y+5}h${Math.min(r.w-60,120)}" stroke="#658591" stroke-width="4"/><text x="${r.x+18}" y="${r.y+35}" class="room-name">${escape(r.name)}</text><text x="${r.x+r.w-18}" y="${r.y+35}" text-anchor="end" class="room-count">${occupants(r).length}/${r.capacity}</text>${furniture(r)}<path d="M${r.x+r.w/2-24} ${r.y<300?r.y+r.h:r.y}h48" stroke="#252a2f" stroke-width="7"/><path d="M${r.x+r.w/2-24} ${r.y<300?r.y+r.h:r.y}v${r.y<300?-40:40}m0 0a40 40 0 0 1 40 ${r.y<300?40:-40}" stroke="#9a9185" stroke-width="1.5" fill="none"/></g>`).join("")}
 ${office.rooms.flatMap(r=>occupants(r).map((a,i)=>{const {x,y}=roomSlot(r,i);return filter&&a.activity!==filter?"":bit(a,x,y); })).join("")}
 <g class="room-hit" role="button" tabindex="0" data-add-room="true" aria-label="扩建示例会议室"><rect x="990" y="30" width="230" height="260" rx="3" fill="none" stroke="#484e58" stroke-dasharray="6 5"/><text x="1105" y="157" text-anchor="middle" class="extend">＋</text><text x="1105" y="185" text-anchor="middle" class="tiny">扩建会议室</text></g></g></svg>`;
}
function focusKey(el:Element|null){
 if(!el||el===document.body)return null;
 const selectors=["id","data-tab","data-filter","data-room","data-agent","data-add-room"];
 for(const attr of selectors){const value=el.getAttribute(attr);if(value!==null){const selector=`[${attr}="${CSS.escape(value)}"]`;return {selector,index:Array.from(document.querySelectorAll(selector)).indexOf(el)};}}
 return null;
}
function render(){
 const focused=focusKey(document.activeElement);
 const running=office.agents.reduce((n,a)=>n+executionState(a.tasks,true,true).running,0), waiting=office.agents.reduce((n,a)=>n+executionState(a.tasks,true,true).waiting,0);
 $("#app").innerHTML=`<header><div class="brand"><span class="brand-bit">▟</span><div><h1>Bit 小屋</h1><span>一间装得下协作的办公室</span></div></div><div class="header-right"><span class="demo-pill"><i></i> 演示模式</span><a href="https://github.com/hekmon8/bit-office" target="_blank" rel="noreferrer" class="icon-link" aria-label="查看开源代码">↗</a></div></header>
 <main><section class="overview"><div><span class="eyebrow">OFFICE / 全部团队</span><h2>宠物们，今天也在忙。</h2><p>公开示例 · ${office.agents.filter(a=>a.online).length} 在线 / ${office.agents.length} 成员 <span class="subtle">在线 ≠ 正在运行</span></p></div><div class="execution-summary"><span><b>${running}</b> 运行</span><span><b>${waiting}</b> 等待</span><span><b>${office.agents.reduce((n,a)=>n+executionState(a.tasks,true,true).blocked,0)}</b> 阻塞</span></div></section>
 <section class="toolbar"><nav aria-label="办公室视图"><button data-tab="map" class="${activeTab==="map"?"active":""}">户型图</button><button data-tab="list" class="${activeTab==="list"?"active":""}">房间列表</button><button data-tab="mcp" class="${activeTab==="mcp"?"active":""}">MCP 接入</button></nav><label class="simulation"><input id="simulation" type="checkbox" ${simulating?"checked":""}/> 模拟活动 <span>仅本页</span></label></section>
 <div class="layout ${activeTab==="list"?"list-layout":""}"><section class="workspace"><div class="legend">${activities.map(s=>`<button data-filter="${s}" aria-pressed="${filter===s}" class="state-chip ${filter===s?"active":""}"><i class="dot ${s}"></i>${labels[s]} <b>${office.agents.filter(a=>a.activity===s).length}</b></button>`).join("")}</div>
 <div class="map-panel" ${activeTab!=="map"?"hidden":""}><div class="map-controls"><span>拖动平移 · 滚轮缩放 · 点击查看</span><div><button id="zoom-out" aria-label="缩小">−</button><button id="reset-view" aria-label="适配全图">适配</button><button id="zoom-in" aria-label="放大">＋</button></div></div><div id="map-stage">${mapSVG()}</div><footer class="map-footer"><span>固定工位 · 独立会议室 · 可扩展走廊</span><span id="zoom-percentage">${Math.round(zoom*100)}%</span></footer></div>
 <div class="room-list" ${activeTab!=="list"?"hidden":""}>${office.rooms.map(roomRow).join("")}<button class="add-room" data-add-room="true">＋ 扩建示例会议室</button></div>
 <div class="mcp-panel" ${activeTab!=="mcp"?"hidden":""}><span class="eyebrow">READ ONLY / HTTP</span><h3>让 ChatGPT 看见示例办公室</h3><p>这个公开 MCP 只读取合成示例数据。尚未连接 Multica，也未验证真实 ChatGPT 授权接入。</p><label>Streamable HTTP 端点</label><code id="endpoint">${location.origin}/mcp</code><button id="copy-endpoint">复制端点</button><h4>可读取</h4><ul><li>办公室全局状态与房间</li><li>Agent 的任务、连接状态和时间</li><li>明确记录的示例任务交接</li></ul><p class="muted">浏览器内的模拟操作不会更改服务器快照。真实数据默认关闭；需另行配置经过授权的身份、工作区和只读范围。</p><a href="https://github.com/hekmon8/bit-office#chatgpt--mcp" target="_blank" rel="noreferrer">查看连接说明 ↗</a></div>
 <div class="freshness"><i></i>${lastSuccessfulReadAt?"最近服务器读取 "+time(lastSuccessfulReadAt):"本地示例生成 "+time(office.observedAt)} · 合成示例 <button id="reset-demo">重置示例</button></div></section>
 <aside><div class="aside-heading"><h3>房间</h3><span>${office.rooms.length} 个空间</span></div><div class="aside-rooms">${office.rooms.map(roomRow).join("")}</div><div class="aside-heading"><h3>动态</h3><span>示例记录</span></div><div class="events">${office.events.slice(0,6).map(e=>`<div><time>${time(e.at)}</time><p>${escape(e.message)}</p></div>`).join("")}</div></aside></div><p class="page-note">Bit 是原创像素宠物。此页面的状态、成员和协作关系均为示例。</p></main>
 <dialog id="detail" aria-labelledby="detail-title"><div class="dialog-head"><span class="eyebrow">BIT OFFICE / 示例详情</span><button id="close-detail" aria-label="关闭详情">×</button></div><div id="detail-content"></div></dialog><div id="toast" role="status"></div>`;
 bind();
 if(focused)(document.querySelectorAll<HTMLElement>(focused.selector)[focused.index])?.focus({preventScroll:true});
}
function roomRow(r:Room){const members=occupants(r);return `<button class="room-row" data-room="${r.id}"><span class="room-icon ${r.kind}">▦</span><span class="room-row-text"><strong>${escape(r.name)}</strong><small>${escape(r.topic)}</small><span>${members.length?members.map(a=>escape(a.name)).join("、"):"暂无成员"}</span></span><span class="capacity">${members.length}/${r.capacity}</span></button>`;}
function toast(message:string){$("#toast").textContent=message;$("#toast").classList.add("visible");setTimeout(()=>$("#toast").classList.remove("visible"),2000);}
function showRoom(id:string){selectedRoom=id;selectedAgent="";const r=office.rooms.find(r=>r.id===id)!;$("#detail-content").innerHTML=`<h2 id="detail-title">${escape(r.name)}</h2><p>${escape(r.topic)} <span class="muted">${occupants(r).length}/${r.capacity}</span></p><div class="detail-agents">${occupants(r).map(a=>`<button data-agent="${a.id}"><i style="background:${a.color}"></i>${escape(a.name)}<span>${labels[a.activity]}</span></button>`).join("")||'<p class="muted">这间房现在空闲。</p>'}</div><p class="muted">房间和讨论均为示例；这里的相邻位置不表示真实任务协作。</p>${r.kind==="meeting"||r.kind==="discussing"?'<button id="finish-meeting" class="primary">结束示例会议</button>':""}`;const dialog=$("#detail") as HTMLDialogElement;if(!dialog.open)dialog.showModal();$("#detail-content").querySelectorAll<HTMLElement>("[data-agent]").forEach(el=>el.onclick=()=>showAgent(el.dataset.agent!));const finish=document.querySelector("#finish-meeting") as HTMLElement|null;if(finish)finish.onclick=()=>{const members=occupants(r).filter(a=>a.online);
 const available=office.rooms.filter(room=>room.kind==="working").reduce((n,room)=>n+room.capacity-occupants(room).length,0);
 if(available<members.length){toast("工位已满，请先释放工位");return;}
 members.forEach(a=>assignActivity(office,a,"working"));r.topic="空闲";addEvent(r.name+" 示例会议结束");dialog.close();};}
function showAgent(id:string){selectedAgent=id;const a=office.agents.find(a=>a.id===id)!;const ex=executionState(a.tasks,true,true);$("#detail-content").innerHTML=`<div class="agent-title"><svg viewBox="-55 -55 110 110" aria-hidden="true">${bit(a,0,0,1.4)}</svg><div><h2 id="detail-title">${escape(a.name)}</h2><p>${labels[a.activity]} · ${a.online?"连接在线":"连接离线"}</p></div></div><div class="facts"><span>任务状态 <b>${ex.label}</b></span><span>运行 ${ex.running} · 等待 ${ex.waiting} · 阻塞 ${ex.blocked}</span><span>最后示例心跳 ${time(a.lastSeenAt)}</span></div><h4>任务与交接</h4>${a.tasks.map(t=>`<div class="task-detail"><strong>${escape(t.title)}</strong><span>${t.status}${t.blocked?" · 阻塞":""}</span>${t.updatedAt?`<span>最后示例任务事件 ${time(t.updatedAt)}</span>`:""}${t.delegatedFrom?`<p>来源任务：${escape(t.delegatedFrom)}</p><p>${escape(t.handoffNote??"")}</p>${t.handoffAt?`<p>示例交接时间 ${time(t.handoffAt)}</p>`:""}`:""}</div>`).join("")||'<p class="muted">没有活动任务示例。</p>'}<label class="field-label" for="demo-activity">切换本页演示动作</label><select id="demo-activity">${activities.map(s=>`<option value="${s}" ${a.activity===s?"selected":""}>${labels[s]}</option>`).join("")}</select><p class="muted">演示动作不改变任务执行状态，也不会调用真实 Agent。</p>`;const d=$("#detail") as HTMLDialogElement;if(!d.open)d.showModal();$("#demo-activity").onchange=()=>{if(moveAgent(a,$<HTMLSelectElement>("#demo-activity").value as Activity))d.close();else showAgent(a.id);};}
function addEvent(message:string){office.events.unshift({at:new Date().toISOString(),message});office.events=office.events.slice(0,20);}
function moveAgent(a:Agent,activity:Activity){if(!assignActivity(office,a,activity)){toast(labels[activity]+"房间已满");return false;}addEvent(a.name+" → "+labels[activity]+" · 仅本页模拟");return true;}
function extendRoom(){if(office.rooms.length>=20){toast("本演示最多 20 间房");return;}const i=office.rooms.length-7, x=1260+Math.floor(i/2)*300,y=i%2?385:30;office.rooms.push({id:"extra-"+i,name:"会议室 "+String.fromCharCode(67+i),kind:"meeting",topic:"空闲",capacity:8,x,y,w:280,h:260});addEvent("扩建了一间示例会议室");render();}
function updateTransform(){const label=document.querySelector("#zoom-percentage");if(label)label.textContent=Math.round(zoom*100)+"%";document.querySelector("#floor-content")?.setAttribute("transform",`translate(${dx} ${dy}) scale(${zoom})`);}
function bind(){
 document.querySelectorAll<HTMLElement>("[data-tab]").forEach(el=>el.onclick=()=>{activeTab=el.dataset.tab as typeof activeTab;render();});
 document.querySelectorAll<HTMLElement>("[data-filter]").forEach(el=>el.onclick=()=>{filter=filter===el.dataset.filter?"":el.dataset.filter as Activity;render();});
 document.querySelectorAll<HTMLElement>("[data-room]").forEach(el=>{el.onclick=()=>showRoom(el.dataset.room!);el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();showRoom(el.dataset.room!);}};});
 document.querySelectorAll<HTMLElement>("[data-agent]").forEach(el=>{el.onclick=e=>{e.stopPropagation();showAgent(el.dataset.agent!);};el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();e.stopPropagation();showAgent(el.dataset.agent!);}};});
 document.querySelectorAll<HTMLElement>("[data-add-room]").forEach(el=>{el.onclick=extendRoom;el.onkeydown=e=>{if(e.key==="Enter"||e.key===" "){e.preventDefault();extendRoom();}};});
 $("#detail").addEventListener("close",()=>render());
 $("#close-detail").onclick=()=>($("#detail") as HTMLDialogElement).close();
 $("#reset-demo").onclick=()=>{office=demoOffice();lastSuccessfulReadAt=null;render();};
 $("#simulation").onchange=()=>{simulating=($("#simulation") as HTMLInputElement).checked;clearInterval(simTimer);if(simulating)simTimer=setInterval(()=>{if(($("#detail") as HTMLDialogElement).open)return;const a=office.agents[Math.floor(Math.random()*office.agents.length)];moveAgent(a,activities[Math.floor(Math.random()*activities.length)]);if(!($("#detail") as HTMLDialogElement).open)render();},6000);render();};
 $("#zoom-in").onclick=()=>{zoom=Math.min(2.4,zoom+.2);updateTransform();};
 $("#zoom-out").onclick=()=>{zoom=Math.max(.6,zoom-.2);updateTransform();};
 $("#reset-view").onclick=()=>{zoom=1;dx=dy=0;updateTransform();};
 $("#copy-endpoint").onclick=async()=>{try{await navigator.clipboard.writeText(location.origin+"/mcp");toast("端点已复制");}catch{toast("请选择端点文字复制");}};
 const stage=$("#map-stage");
 const svgPoint=(x:number,y:number)=>{const svg=$<SVGSVGElement>("#floor"),matrix=svg.getScreenCTM();return matrix?new DOMPoint(x,y).matrixTransform(matrix.inverse()):new DOMPoint(x,y);};
 let start:{x:number;y:number;dx:number;dy:number}|null=null,dragged=false;
 stage.onpointerdown=e=>{if(start)return;if((e.target as Element).closest("[data-agent], [data-room], [data-add-room]"))return;const point=svgPoint(e.clientX,e.clientY);start={x:point.x,y:point.y,dx,dy};dragged=false;stage.setPointerCapture(e.pointerId);};
 stage.onpointermove=e=>{if(start){dragged=true;const point=svgPoint(e.clientX,e.clientY);dx=start.dx+point.x-start.x;dy=start.dy+point.y-start.y;updateTransform();}};
 stage.onpointerup=()=>{start=null;};stage.onpointercancel=()=>{start=null;};
 stage.addEventListener("wheel",e=>{e.preventDefault();zoom=Math.max(.6,Math.min(2.4,zoom+(e.deltaY<0?.1:-.1)));updateTransform();},{passive:false});
}
render();
fetch("/api/demo/state").then(r=>{if(!r.ok)throw new Error("read failed");return r.json();}).then(data=>{if(!validateOffice(data))throw new Error("invalid demo state");lastSuccessfulReadAt=new Date().toISOString();if(!($("#detail") as HTMLDialogElement).open){office=data;render();}}).catch(()=>{toast("使用内置示例 · 未连接服务器");});
